### ISSUE TITLE
const slots = this.slots && this.slots()

### ISSUE THREAD

**Issue by yaojin2070** [hyk51594176/mcommon#7]
这个是什么意思, 我找遍了官网都没找到, 有文档吗?

**Comment by hyk51594176** [comment]
vue functional的函数组件 render的第二个参数context会有这个属性

**Comment by hyk51594176** [comment]
https://cn.vuejs.org/v2/guide/render-function.html#%E5%87%BD%E6%95%B0%E5%BC%8F%E7%BB%84%E4%BB%B6

**Comment by yaojin2070** [comment]
嗯,昨晚看了下,没认真看到, 没想到你这么快回复我了,没看到邮箱, 我最近打算将你的组件放到一个脚手架中,并且将你的代码认真阅读一遍,可能会写文档出来, 如果有不明白的地方,希望可以方便的向你提问,我的vx: 87442144  可以的话,方便加下吗?

**Comment by yaojin2070** [comment]
> https://cn.vuejs.org/v2/guide/render-function.html#%E5%87%BD%E6%95%B0%E5%BC%8F%E7%BB%84%E4%BB%B6



> vue functional的无状态组件 render的第二个参数context会有这个属性

嗯,昨晚看了下,没认真看到, 没想到你这么快回复我了,没看到邮箱, 我最近打算将你的组件放到一个脚手架中,并且将你的代码认真阅读一遍,可能会写文档出来, 如果有不明白的地方,希望可以方便的向你提问,我的vx: 87442144 可以的话,方便加下吗?
